name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
#    - name: Build samples
#      run: |
#        msbuild samples/ElmahIo.Samples.XamarinAndroid/ElmahIo.Samples.XamarinAndroid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
#        msbuild samples/ElmahIo.Samples.XamarinForms/ElmahIo.Samples.XamarinForms.Android/ElmahIo.Samples.XamarinForms.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
#        msbuild samples/ElmahIo.Samples.XamarinForms.iOS/ElmahIo.Samples.XamarinForms.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
#        msbuild samples/ElmahIo.Samples.XamariniOS/ElmahIo.Samples.XamariniOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
    - name: Install dependencies
      run: |
        dotnet restore src/Elmah.Io.Xamarin/Elmah.Io.Xamarin.csproj
        dotnet restore test/Elmah.Io.Xamarin.Test/Elmah.Io.Xamarin.Test.csproj
    - name: Build
      run: msbuild src/Elmah.Io.Xamarin/Elmah.Io.Xamarin.csproj -p:Configuration=Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal test/Elmah.Io.Xamarin.Test/Elmah.Io.Xamarin.Test.csproj
    - name: Pack
      run: nuget pack Elmah.Io.Xamarin.nuspec -Version 4.0.${{ github.run_number }}-pre -Properties Configuration=Release -Properties Commit=${{ github.sha }}
    - name: Push
      run: dotnet nuget push Elmah.Io.Xamarin.4.0.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}
